Add config controller
EvgeniyZZ/skale.py pull request #5
Opened 2024-11-14 11:59 UTC by OleksanderSalamatov

- add full support for config-controller
- fixed minor linter warnings in paymaster predeployed

2024-11-14 15:32 UTC, yatsunastya approved these changes

2024-11-14 16:29 UTC, EvgeniyZZ requested changes
To discuss

2024-11-15 13:32 UTC, EvgeniyZZ commented on skale/contracts/config_controller/config_controller.py
> +    def default_admin_role(self) -> hex:
Smart contracts expect to receive bytes. Use bytes type for low level interaction.

2024-11-15 13:32 UTC, EvgeniyZZ commented on skale/contracts/config_controller/config_controller.py
> +from eth_typing import ChecksumAddress
Use:
from eth_typing import ChecksumAddress, HexStr
insted of -> hex: 
correct -> HexStr

2024-11-15 13:32 UTC, EvgeniyZZ commented on skale/contracts/config_controller/config_controller.py
> +from web3.contract.contract import ContractFunction
Use TxRes

2024-12-04 15:40 UTC, EvgeniyZZ approved these changes

2024-12-04 15:40 UTC, EvgeniyZZ approved these changes

2024-12-04 15:40 UTC, merged